"""
SHL Product Catalog - Individual Test Solutions
Scraped from https://www.shl.com/solutions/products/product-catalog/
Type 1 = Individual Test Solutions (Pre-packaged Job Solutions excluded)

Test Types:
A = Ability & Aptitude
B = Biodata & Situational Judgement  
C = Competencies
D = Development & 360
E = Assessment Exercises
K = Knowledge & Skills
P = Personality & Behavior
S = Simulations
"""

CATALOG = [
    # ── Ability & Aptitude (A) ──────────────────────────────────────────────
    {
        "name": "Verify Numerical Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-numerical-reasoning/",
        "description": "Measures the ability to work with numerical data presented in various formats including graphs, charts and tables.",
        "test_type": "A",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)", "English International", "French", "German", "Spanish", "Chinese Simplified"],
        "keywords": ["numerical", "reasoning", "data analysis", "quantitative", "mathematics", "statistics", "finance"],
    },
    {
        "name": "Verify Verbal Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-verbal-reasoning/",
        "description": "Measures the ability to comprehend and evaluate logical arguments presented in written form.",
        "test_type": "A",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 19,
        "languages": ["English (USA)", "English International", "French", "German", "Spanish"],
        "keywords": ["verbal", "reasoning", "comprehension", "communication", "language", "reading"],
    },
    {
        "name": "Verify Inductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-inductive-reasoning/",
        "description": "Measures the ability to identify rules and patterns and apply them to new situations; assesses abstract problem-solving.",
        "test_type": "A",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 24,
        "languages": ["English (USA)", "English International", "French", "German", "Spanish"],
        "keywords": ["inductive", "reasoning", "abstract", "pattern", "logic", "problem solving", "analytical"],
    },
    {
        "name": "Verify Deductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-deductive-reasoning/",
        "description": "Measures ability to draw logical conclusions from given information and apply rules to specific situations.",
        "test_type": "A",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)", "English International", "French", "German", "Spanish"],
        "keywords": ["deductive", "reasoning", "logic", "analytical", "critical thinking"],
    },
    {
        "name": "SHL Verify Interactive G+",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/shl-verify-interactive-g/",
        "description": "A test of general cognitive ability (G+) that generates accurate assessments of Deductive, Inductive, and Numerical Reasoning simultaneously. Adaptive/IRT based. Completion time 36 minutes.",
        "test_type": "A",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 36,
        "languages": ["English (USA)", "English International", "Chinese Traditional", "Korean", "Danish", "Swedish", "Norwegian", "Finnish"],
        "keywords": ["general ability", "cognitive", "G+", "interactive", "numerical", "inductive", "deductive", "reasoning", "intelligence"],
    },
    {
        "name": "Verify Interactive – Numerical Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-interactive-numerical-reasoning/",
        "description": "Interactive adaptive numerical reasoning test measuring ability to analyze numerical data in graphs and tables.",
        "test_type": "A",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 18,
        "languages": ["English (USA)", "English International"],
        "keywords": ["numerical", "reasoning", "interactive", "adaptive", "quantitative", "data", "finance"],
    },
    {
        "name": "Verify Interactive – Inductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-interactive-inductive-reasoning/",
        "description": "Interactive adaptive inductive reasoning test measuring abstract pattern recognition and problem-solving.",
        "test_type": "A",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 18,
        "languages": ["English (USA)", "English International"],
        "keywords": ["inductive", "reasoning", "interactive", "adaptive", "abstract", "pattern", "logic"],
    },
    {
        "name": "Verify Interactive – Deductive Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verify-interactive-deductive-reasoning/",
        "description": "Interactive adaptive deductive reasoning test measuring ability to derive correct conclusions from given information.",
        "test_type": "A",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 18,
        "languages": ["English (USA)", "English International"],
        "keywords": ["deductive", "reasoning", "interactive", "adaptive", "logical", "conclusions"],
    },
    {
        "name": "Numerical Calculation",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/numerical-calculation/",
        "description": "Measures the ability to perform basic arithmetic calculations quickly and accurately without a calculator.",
        "test_type": "A",
        "job_levels": ["Entry-Level", "General Population", "Graduate"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 10,
        "languages": ["English (USA)", "English International"],
        "keywords": ["numerical", "calculation", "arithmetic", "math", "clerical", "entry level"],
    },
    {
        "name": "Mechanical Comprehension",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/mechanical-comprehension/",
        "description": "Measures understanding of basic mechanical and physical principles as applied in practical situations.",
        "test_type": "A",
        "job_levels": ["Entry-Level", "General Population"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["mechanical", "technical", "engineering", "physical", "manufacturing", "industrial"],
    },
    {
        "name": "Verbal Ability",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/verbal-ability/",
        "description": "Measures verbal ability including word usage, sentence completion and grammar for clerical/entry-level roles.",
        "test_type": "A",
        "job_levels": ["Entry-Level", "General Population"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["verbal", "language", "grammar", "clerical", "entry level", "communication"],
    },
    {
        "name": "Reading Comprehension",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/reading-comprehension/",
        "description": "Measures ability to understand and interpret written information for clerical and general population.",
        "test_type": "A",
        "job_levels": ["Entry-Level", "General Population"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["reading", "comprehension", "verbal", "clerical", "administrative"],
    },
    {
        "name": "Numerical Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/numerical-reasoning/",
        "description": "Assesses general numerical reasoning ability for managerial and professional candidates.",
        "test_type": "A",
        "job_levels": ["Manager", "Professional Individual Contributor", "Mid-Professional"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)", "English International"],
        "keywords": ["numerical", "quantitative", "reasoning", "manager", "finance", "data"],
    },
    # ── Biodata & Situational Judgment (B) ─────────────────────────────────
    {
        "name": "Situational Judgement Test (SJT)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/situational-judgement-test/",
        "description": "Measures judgment in work-related situations. Assesses decision-making and problem-solving in realistic workplace scenarios.",
        "test_type": "B",
        "job_levels": ["Entry-Level", "Graduate", "Manager", "Mid-Professional", "Supervisor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English (USA)", "English International"],
        "keywords": ["situational judgment", "SJT", "decision making", "judgment", "workplace scenarios", "leadership", "soft skills"],
    },
    {
        "name": "Realistic Job Preview",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/realistic-job-preview/",
        "description": "Provides candidates with a realistic preview of the job and assesses fit through self-assessment and preference questions.",
        "test_type": "B",
        "job_levels": ["Entry-Level", "General Population"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["job preview", "fit", "culture", "self-assessment", "entry level", "retention"],
    },
    # ── Personality & Behavior (P) ──────────────────────────────────────────
    {
        "name": "OPQ32r (Occupational Personality Questionnaire)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/opq32r/",
        "description": "SHL's flagship personality questionnaire measuring 32 dimensions of personality related to work performance. Provides rich insights into an individual's preferred style of working, relating to others, and dealing with emotions.",
        "test_type": "P",
        "job_levels": ["Director", "Executive", "Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)", "English International", "French", "German", "Spanish", "Arabic", "Chinese Simplified", "Chinese Traditional", "Dutch", "Italian", "Japanese", "Korean", "Portuguese", "Russian"],
        "keywords": ["personality", "OPQ", "OPQ32", "behavior", "leadership", "interpersonal", "communication", "work style", "motivation", "culture fit"],
    },
    {
        "name": "OPQ32n",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/opq32n/",
        "description": "Normative version of OPQ32 measuring 32 personality dimensions with normative scoring for work performance prediction.",
        "test_type": "P",
        "job_levels": ["Director", "Executive", "Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)", "English International", "French", "German", "Spanish"],
        "keywords": ["personality", "OPQ", "OPQ32n", "normative", "behavior", "leadership", "work style"],
    },
    {
        "name": "Motivational Questionnaire (MQ)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/motivational-questionnaire/",
        "description": "Measures the factors that energize, drive, and motivate an individual's behavior at work across 18 dimensions.",
        "test_type": "P",
        "job_levels": ["Director", "Executive", "Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)", "English International", "French", "German", "Spanish"],
        "keywords": ["motivation", "MQ", "values", "drive", "engagement", "culture fit", "retention"],
    },
    {
        "name": "RemoteWorkQ",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/remoteworkq/",
        "description": "Assesses a candidate's ability and attitude toward working effectively in a remote or hybrid work environment.",
        "test_type": "P",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)", "English International"],
        "keywords": ["remote work", "hybrid", "work from home", "virtual", "self-management", "autonomy"],
    },
    # ── Knowledge & Skills (K) ──────────────────────────────────────────────
    # Programming Languages
    {
        "name": "Java 8 (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/java-8-new/",
        "description": "Multi-choice test measuring knowledge of Java 8 features including lambda expressions, streams, functional interfaces, date/time API.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)"],
        "keywords": ["Java", "Java 8", "programming", "software development", "backend", "developer", "lambda", "streams"],
    },
    {
        "name": "Core Java (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/core-java-new/",
        "description": "Multi-choice test measuring knowledge of core Java programming including OOP, collections, exceptions, and concurrency.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)"],
        "keywords": ["Java", "core Java", "OOP", "programming", "software development", "backend", "developer"],
    },
    {
        "name": "Python (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/python-new/",
        "description": "Multi-choice test measuring knowledge of Python programming including syntax, data structures, libraries, and OOP.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)"],
        "keywords": ["Python", "programming", "data science", "machine learning", "scripting", "developer", "backend"],
    },
    {
        "name": "JavaScript (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/javascript-new/",
        "description": "Multi-choice test measuring knowledge of JavaScript including ES6+, DOM manipulation, async patterns, and frameworks.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["JavaScript", "JS", "frontend", "web development", "programming", "developer", "ES6", "Node"],
    },
    {
        "name": "C# (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/c-sharp-new/",
        "description": "Multi-choice test measuring knowledge of C# programming including .NET, OOP concepts, LINQ, and async programming.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)"],
        "keywords": ["C#", ".NET", "dotnet", "programming", "Microsoft", "backend", "software development"],
    },
    {
        "name": "C Programming (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/c-programming-new/",
        "description": "Multi-choice test measuring knowledge of C programming including pointers, memory management, data structures.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 10,
        "languages": ["English (USA)"],
        "keywords": ["C", "programming", "systems", "embedded", "low-level", "developer"],
    },
    {
        "name": "C++ (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/c-plus-plus-new/",
        "description": "Multi-choice test measuring knowledge of C++ including OOP, STL, templates, and modern C++ features.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["C++", "programming", "systems", "game development", "embedded", "developer"],
    },
    {
        "name": "PHP (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/php-new/",
        "description": "Multi-choice test measuring knowledge of PHP web development including OOP, frameworks, and database integration.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["PHP", "web development", "backend", "programming", "developer"],
    },
    {
        "name": "Ruby (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/ruby-new/",
        "description": "Multi-choice test measuring knowledge of Ruby programming and Ruby on Rails framework.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Ruby", "Rails", "programming", "web development", "backend", "developer"],
    },
    {
        "name": "Swift (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/swift-new/",
        "description": "Multi-choice test measuring knowledge of Swift programming for iOS/macOS development.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Swift", "iOS", "macOS", "Apple", "mobile", "programming", "developer"],
    },
    {
        "name": "Kotlin (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/kotlin-new/",
        "description": "Multi-choice test measuring knowledge of Kotlin programming for Android and server-side development.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Kotlin", "Android", "mobile", "JVM", "programming", "developer"],
    },
    {
        "name": "Scala (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/scala-new/",
        "description": "Multi-choice test measuring knowledge of Scala programming including functional programming and Akka.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Scala", "functional programming", "big data", "Spark", "JVM", "developer"],
    },
    {
        "name": "Go (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/go-new/",
        "description": "Multi-choice test measuring knowledge of Go (Golang) programming including concurrency, interfaces, and standard library.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Go", "Golang", "programming", "backend", "microservices", "cloud", "developer"],
    },
    {
        "name": "R (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/r-new/",
        "description": "Multi-choice test measuring knowledge of R programming for statistical analysis and data science.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["R", "statistics", "data science", "data analysis", "programming", "analytics"],
    },
    {
        "name": "TypeScript (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/typescript-new/",
        "description": "Multi-choice test measuring knowledge of TypeScript including types, interfaces, generics, and decorators.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["TypeScript", "JavaScript", "frontend", "web development", "programming", "developer"],
    },
    # Web frameworks
    {
        "name": "Angular (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/angular-new/",
        "description": "Multi-choice test measuring knowledge of Angular framework including components, services, routing, and RxJS.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Angular", "TypeScript", "frontend", "web development", "framework", "developer"],
    },
    {
        "name": "React (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/react-new/",
        "description": "Multi-choice test measuring knowledge of React including hooks, state management, and component lifecycle.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["React", "JavaScript", "frontend", "web development", "UI", "developer"],
    },
    {
        "name": "Spring (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/spring-new/",
        "description": "Multi-choice test measuring knowledge of Spring core, AOP, IOC container and transactions.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Spring", "Spring Boot", "Java", "backend", "microservices", "developer"],
    },
    {
        "name": "Node.js (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/node-js-new/",
        "description": "Multi-choice test measuring knowledge of Node.js including event loop, modules, Express, and async patterns.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Node.js", "JavaScript", "backend", "server-side", "Express", "developer"],
    },
    # Databases
    {
        "name": "SQL (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sql-new/",
        "description": "Multi-choice test measuring SQL knowledge including queries, joins, subqueries, and database design.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor", "Graduate"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["SQL", "database", "queries", "relational", "MySQL", "PostgreSQL", "data", "analytics"],
    },
    {
        "name": "Oracle Database (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/oracle-database-new/",
        "description": "Multi-choice test measuring knowledge of Oracle Database including PL/SQL, performance tuning, and administration.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)"],
        "keywords": ["Oracle", "database", "PL/SQL", "DBA", "enterprise", "data"],
    },
    {
        "name": "MySQL (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/mysql-new/",
        "description": "Multi-choice test measuring knowledge of MySQL database including queries, stored procedures, and optimization.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["MySQL", "database", "SQL", "backend", "web development"],
    },
    {
        "name": "MongoDB (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/mongodb-new/",
        "description": "Multi-choice test measuring knowledge of MongoDB including document model, aggregation, and indexing.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["MongoDB", "NoSQL", "database", "backend", "cloud", "developer"],
    },
    # Cloud & DevOps
    {
        "name": "Amazon Web Services (AWS) (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/amazon-web-services-new/",
        "description": "Multi-choice test measuring knowledge of AWS services including EC2, S3, Lambda, RDS, and IAM.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)"],
        "keywords": ["AWS", "cloud", "Amazon", "EC2", "S3", "Lambda", "cloud computing", "DevOps"],
    },
    {
        "name": "Microsoft Azure (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/microsoft-azure-new/",
        "description": "Multi-choice test measuring knowledge of Microsoft Azure cloud services including compute, storage, and networking.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)"],
        "keywords": ["Azure", "Microsoft", "cloud", "cloud computing", "DevOps", "developer"],
    },
    {
        "name": "Google Cloud Platform (GCP) (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/google-cloud-platform-new/",
        "description": "Multi-choice test measuring knowledge of GCP services including Compute Engine, BigQuery, and Kubernetes Engine.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)"],
        "keywords": ["GCP", "Google Cloud", "cloud", "BigQuery", "Kubernetes", "cloud computing"],
    },
    {
        "name": "Docker (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/docker-new/",
        "description": "Multi-choice test measuring knowledge of Docker including containers, images, Docker Compose, and networking.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["Docker", "containers", "DevOps", "containerization", "microservices", "cloud"],
    },
    {
        "name": "Kubernetes (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/kubernetes-new/",
        "description": "Multi-choice test measuring knowledge of Kubernetes including pods, deployments, services, and cluster management.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Kubernetes", "K8s", "containers", "DevOps", "orchestration", "cloud", "microservices"],
    },
    {
        "name": "Agile Software Development",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/agile-software-development/",
        "description": "Multi-choice test measuring knowledge of agile methodology, scrum, feature driven software development, incremental and iterative development.",
        "test_type": "K",
        "job_levels": ["Graduate", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 7,
        "languages": ["English (USA)"],
        "keywords": ["Agile", "Scrum", "software development", "methodology", "sprint", "kanban", "project management"],
    },
    {
        "name": "Git (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/git-new/",
        "description": "Multi-choice test measuring knowledge of Git version control including branching, merging, rebasing, and workflows.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 10,
        "languages": ["English (USA)"],
        "keywords": ["Git", "version control", "DevOps", "source control", "developer"],
    },
    {
        "name": "Linux (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/linux-new/",
        "description": "Multi-choice test measuring knowledge of Linux including shell commands, file system, permissions, and system administration.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Linux", "Unix", "shell", "sysadmin", "DevOps", "infrastructure", "system administration"],
    },
    # Data
    {
        "name": "Machine Learning (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/machine-learning-new/",
        "description": "Multi-choice test measuring knowledge of machine learning algorithms, model evaluation, and best practices.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["machine learning", "ML", "AI", "data science", "algorithms", "deep learning", "neural networks"],
    },
    {
        "name": "Data Science (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/data-science-new/",
        "description": "Multi-choice test measuring knowledge of data science including statistics, Python/R, and data visualization.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["data science", "analytics", "statistics", "Python", "R", "visualization", "machine learning"],
    },
    {
        "name": "Hadoop (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/hadoop-new/",
        "description": "Multi-choice test measuring knowledge of Hadoop ecosystem including HDFS, MapReduce, Hive, and HBase.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Hadoop", "big data", "HDFS", "MapReduce", "data engineering", "Spark"],
    },
    {
        "name": "Apache Spark (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/apache-spark-new/",
        "description": "Multi-choice test measuring knowledge of Apache Spark for big data processing and analytics.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Spark", "big data", "data engineering", "distributed computing", "Scala", "Python"],
    },
    # Cybersecurity
    {
        "name": "Cybersecurity (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/cybersecurity-new/",
        "description": "Multi-choice test measuring knowledge of cybersecurity including network security, cryptography, and threat analysis.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)"],
        "keywords": ["cybersecurity", "security", "network security", "information security", "CISSP", "threat", "firewall"],
    },
    {
        "name": "Network Security (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/network-security-new/",
        "description": "Multi-choice test measuring knowledge of network security concepts, protocols, and best practices.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["network security", "security", "firewalls", "VPN", "intrusion detection", "cybersecurity"],
    },
    # Testing & QA
    {
        "name": "Manual Testing (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/manual-testing-new/",
        "description": "Multi-choice test measuring knowledge of software testing lifecycle, testing tools and techniques, design of test cases and generation of test reports.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["testing", "QA", "quality assurance", "test cases", "software testing", "SDLC"],
    },
    {
        "name": "Automation Testing (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/automation-testing-new/",
        "description": "Multi-choice test measuring knowledge of automated testing frameworks including Selenium, JUnit, and TestNG.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["automation testing", "Selenium", "QA", "test automation", "CI/CD", "software testing"],
    },
    # Microsoft Office
    {
        "name": "MS Excel (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/ms-excel-new/",
        "description": "Multi-choice test measuring ability to use MS Excel to maintain, organize, analyze and present numeric data.",
        "test_type": "K",
        "job_levels": ["Entry-Level", "Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)", "Spanish", "French", "Portuguese (Brazil)"],
        "keywords": ["Excel", "Microsoft Excel", "spreadsheet", "data analysis", "finance", "administrative", "reporting"],
    },
    {
        "name": "MS Word (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/ms-word-new/",
        "description": "Multi-choice test measuring ability to use MS Word for document creation, formatting, and editing.",
        "test_type": "K",
        "job_levels": ["Entry-Level", "Graduate", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)", "Spanish", "French"],
        "keywords": ["Word", "Microsoft Word", "document", "administrative", "writing", "office"],
    },
    {
        "name": "MS PowerPoint (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/ms-powerpoint-new/",
        "description": "Multi-choice test measuring ability to use MS PowerPoint for presentations.",
        "test_type": "K",
        "job_levels": ["Entry-Level", "Graduate", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["PowerPoint", "Microsoft PowerPoint", "presentation", "administrative", "office"],
    },
    {
        "name": ".NET Framework 4.5",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/net-framework-4-5/",
        "description": "Multi-choice test measuring knowledge of .NET Framework 4.5 including CLR, BCL, and ASP.NET.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": True,
        "duration_minutes": 30,
        "languages": ["English (USA)"],
        "keywords": [".NET", "dotnet", "C#", "Microsoft", "backend", "developer", "ASP.NET"],
    },
    {
        "name": "Android Development (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/android-development-new/",
        "description": "Multi-choice test measuring knowledge of Android app development including activities, intents, and UI components.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 7,
        "languages": ["English (USA)"],
        "keywords": ["Android", "mobile", "app development", "Kotlin", "Java", "developer"],
    },
    {
        "name": "iOS Development (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/ios-development-new/",
        "description": "Multi-choice test measuring knowledge of iOS app development including Swift, UIKit, and Xcode.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["iOS", "mobile", "app development", "Swift", "Xcode", "Apple", "developer"],
    },
    {
        "name": "React Native (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/react-native-new/",
        "description": "Multi-choice test measuring knowledge of React Native for cross-platform mobile development.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["React Native", "mobile", "cross-platform", "JavaScript", "app development", "developer"],
    },
    # Business skills
    {
        "name": "Accounting (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/accounting-new/",
        "description": "Multi-choice test measuring knowledge of accounting principles, financial reporting, and bookkeeping.",
        "test_type": "K",
        "job_levels": ["Graduate", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["accounting", "finance", "GAAP", "financial reporting", "bookkeeping", "CPA"],
    },
    {
        "name": "Financial Accounting (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/financial-accounting-new/",
        "description": "Measures knowledge of financial accounting standards, financial statements, and accounting cycle.",
        "test_type": "K",
        "job_levels": ["Graduate", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["financial accounting", "finance", "GAAP", "financial statements", "accounting"],
    },
    {
        "name": "Business Analysis (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/business-analysis-new/",
        "description": "Multi-choice test measuring knowledge of business analysis techniques, requirements gathering, and process modeling.",
        "test_type": "K",
        "job_levels": ["Graduate", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["business analysis", "BA", "requirements", "process modeling", "stakeholder", "SDLC", "project management"],
    },
    {
        "name": "Project Management (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/project-management-new/",
        "description": "Multi-choice test measuring knowledge of project management principles, methodologies, and best practices including PMP.",
        "test_type": "K",
        "job_levels": ["Manager", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["project management", "PMP", "Agile", "stakeholder", "planning", "risk management", "PMO"],
    },
    {
        "name": "Human Resources (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/human-resources-new/",
        "description": "Multi-choice test measuring knowledge of HR fundamentals including recruitment, compensation, and employment law.",
        "test_type": "K",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["HR", "human resources", "recruitment", "compensation", "benefits", "employment law", "HRBP"],
    },
    {
        "name": "Sales Skills (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sales-skills-new/",
        "description": "Multi-choice test measuring knowledge of sales techniques, customer relationship management, and pipeline management.",
        "test_type": "K",
        "job_levels": ["Entry-Level", "Mid-Professional", "Professional Individual Contributor", "Supervisor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["sales", "CRM", "pipeline", "account management", "negotiation", "customer"],
    },
    {
        "name": "Marketing (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/marketing-new/",
        "description": "Multi-choice test measuring knowledge of marketing principles, digital marketing, and market research.",
        "test_type": "K",
        "job_levels": ["Graduate", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["marketing", "digital marketing", "SEO", "brand", "market research", "campaign"],
    },
    # ── Simulations (S) ─────────────────────────────────────────────────────
    {
        "name": "Coding Simulation – Java",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/coding-simulation-java/",
        "description": "Practical coding simulation where candidates write working Java code in an IDE-like environment to solve realistic problems.",
        "test_type": "S",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 60,
        "languages": ["English (USA)"],
        "keywords": ["Java", "coding", "simulation", "programming", "developer", "practical", "hands-on"],
    },
    {
        "name": "Coding Simulation – Python",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/coding-simulation-python/",
        "description": "Practical coding simulation where candidates write working Python code to solve real-world problems.",
        "test_type": "S",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 60,
        "languages": ["English (USA)"],
        "keywords": ["Python", "coding", "simulation", "programming", "developer", "data science", "practical"],
    },
    {
        "name": "Coding Simulation – JavaScript",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/coding-simulation-javascript/",
        "description": "Practical coding simulation where candidates write working JavaScript code for frontend and backend problems.",
        "test_type": "S",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 60,
        "languages": ["English (USA)"],
        "keywords": ["JavaScript", "coding", "simulation", "programming", "developer", "frontend", "practical"],
    },
    {
        "name": "Coding Simulation – SQL",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/coding-simulation-sql/",
        "description": "Practical coding simulation where candidates write SQL queries to retrieve and manipulate data.",
        "test_type": "S",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English (USA)"],
        "keywords": ["SQL", "database", "coding simulation", "queries", "data analyst", "practical"],
    },
    {
        "name": "Contact Center Simulation",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/contact-center-simulation/",
        "description": "Simulates a contact center environment to assess customer service handling, multitasking, and communication skills.",
        "test_type": "S",
        "job_levels": ["Entry-Level", "General Population"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English (USA)"],
        "keywords": ["contact center", "customer service", "call center", "simulation", "multitasking", "communication"],
    },
    {
        "name": "Inbasket (E-Tray) Simulation",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/inbasket-simulation/",
        "description": "Simulates a typical work inbox scenario to assess prioritization, decision-making, and managerial judgment.",
        "test_type": "S",
        "job_levels": ["Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English (USA)"],
        "keywords": ["in-basket", "e-tray", "simulation", "prioritization", "management", "decision making", "leadership"],
    },
    # ── Competencies (C) ────────────────────────────────────────────────────
    {
        "name": "Competency Based Interview Tool",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/competency-based-interview-tool/",
        "description": "Structured interview guide aligned to the Universal Competency Framework to assess key behavioral competencies.",
        "test_type": "C",
        "job_levels": ["Director", "Executive", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 60,
        "languages": ["English (USA)"],
        "keywords": ["competency", "interview", "behavioral", "UCF", "leadership", "structured interview"],
    },
    {
        "name": "Universal Competency Framework (UCF) Assessment",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/ucf-assessment/",
        "description": "Measures core behavioral competencies aligned to the Universal Competency Framework covering 20 competency areas.",
        "test_type": "C",
        "job_levels": ["Director", "Executive", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English (USA)", "English International"],
        "keywords": ["competency", "behavioral", "UCF", "leadership", "teamwork", "communication", "management"],
    },
    # ── Development & 360 (D) ───────────────────────────────────────────────
    {
        "name": "360 Degree Feedback",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/360-degree-feedback/",
        "description": "Multi-rater feedback tool that collects assessment from managers, peers, and direct reports on behavioral competencies.",
        "test_type": "D",
        "job_levels": ["Director", "Executive", "Front Line Manager", "Manager", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English (USA)", "English International"],
        "keywords": ["360 feedback", "multi-rater", "development", "leadership", "performance", "management"],
    },
    # ── Assessment Exercises (E) ─────────────────────────────────────────────
    {
        "name": "Group Exercise",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/group-exercise/",
        "description": "Collaborative assessment exercise where candidates work together to solve a business problem, assessing teamwork and leadership.",
        "test_type": "E",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 45,
        "languages": ["English (USA)"],
        "keywords": ["group exercise", "teamwork", "collaboration", "leadership", "assessment center"],
    },
    {
        "name": "Presentation Exercise",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/presentation-exercise/",
        "description": "Assessment exercise where candidates prepare and deliver a presentation on a business topic to assessors.",
        "test_type": "E",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English (USA)"],
        "keywords": ["presentation", "communication", "leadership", "assessment center", "stakeholder management"],
    },
    {
        "name": "Role Play Exercise",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/role-play-exercise/",
        "description": "Simulated one-on-one meeting exercise assessing communication, interpersonal skills, and problem-solving.",
        "test_type": "E",
        "job_levels": ["Graduate", "Manager", "Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English (USA)"],
        "keywords": ["role play", "interpersonal", "communication", "customer", "negotiation", "assessment center"],
    },
    # ── Additional Knowledge & Skills ────────────────────────────────────────
    {
        "name": "Swing (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/swing-new/",
        "description": "Multi-choice test measuring knowledge of components, containers, layouts and event handling in Swing.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 10,
        "languages": ["English (USA)"],
        "keywords": ["Swing", "Java", "GUI", "desktop", "developer"],
    },
    {
        "name": "COBOL (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/cobol-new/",
        "description": "Multi-choice test measuring knowledge of COBOL programming language for mainframe development.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["COBOL", "mainframe", "legacy", "banking", "enterprise", "developer"],
    },
    {
        "name": "Salesforce (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/salesforce-new/",
        "description": "Multi-choice test measuring knowledge of Salesforce CRM platform including administration and development.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["Salesforce", "CRM", "cloud", "sales", "developer", "administrator"],
    },
    {
        "name": "SAP (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/sap-new/",
        "description": "Multi-choice test measuring knowledge of SAP ERP including modules, configuration, and business processes.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 25,
        "languages": ["English (USA)"],
        "keywords": ["SAP", "ERP", "enterprise", "business processes", "consultant", "developer"],
    },
    {
        "name": "Tableau (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/tableau-new/",
        "description": "Multi-choice test measuring knowledge of Tableau for data visualization and business intelligence.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["Tableau", "data visualization", "BI", "business intelligence", "analytics", "data"],
    },
    {
        "name": "Power BI (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/power-bi-new/",
        "description": "Multi-choice test measuring knowledge of Microsoft Power BI for data visualization and reporting.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["Power BI", "Microsoft", "data visualization", "BI", "business intelligence", "reporting", "analytics"],
    },
    {
        "name": "DevOps (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/devops-new/",
        "description": "Multi-choice test measuring knowledge of DevOps principles, CI/CD pipelines, and infrastructure automation.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["DevOps", "CI/CD", "automation", "infrastructure", "pipeline", "Jenkins", "cloud"],
    },
    {
        "name": "Terraform (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/terraform-new/",
        "description": "Multi-choice test measuring knowledge of Terraform infrastructure as code for cloud provisioning.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["Terraform", "infrastructure as code", "IaC", "cloud", "DevOps", "AWS", "Azure"],
    },
    {
        "name": "Strategic Reasoning",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/strategic-reasoning/",
        "description": "Measures ability to think strategically, analyze complex business situations, and formulate effective strategies.",
        "test_type": "A",
        "job_levels": ["Director", "Executive", "Manager"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 30,
        "languages": ["English (USA)", "English International"],
        "keywords": ["strategic thinking", "leadership", "executive", "director", "business strategy", "senior management"],
    },
    {
        "name": "Supervisory Skills (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/supervisory-skills-new/",
        "description": "Measures knowledge and judgment related to supervisory responsibilities including coaching, feedback, and team management.",
        "test_type": "K",
        "job_levels": ["Front Line Manager", "Supervisor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["supervisor", "management", "coaching", "team management", "leadership", "front line"],
    },
    {
        "name": "Customer Service (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/customer-service-new/",
        "description": "Measures knowledge and skills related to providing excellent customer service including communication and problem resolution.",
        "test_type": "K",
        "job_levels": ["Entry-Level", "General Population", "Graduate"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)", "Spanish", "French"],
        "keywords": ["customer service", "customer support", "communication", "service", "retail", "call center"],
    },
    {
        "name": "Basic Computer Literacy (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/basic-computer-literacy-new/",
        "description": "Measures fundamental computer skills including basic internet usage, file management, and common software applications.",
        "test_type": "K",
        "job_levels": ["Entry-Level", "General Population"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["computer literacy", "IT basics", "technology", "entry level", "administrative"],
    },
    {
        "name": "Data Entry Speed and Accuracy (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/data-entry-speed-accuracy-new/",
        "description": "Measures speed and accuracy of data entry skills for clerical and administrative roles.",
        "test_type": "K",
        "job_levels": ["Entry-Level", "General Population"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 10,
        "languages": ["English (USA)"],
        "keywords": ["data entry", "typing", "clerical", "administrative", "accuracy", "speed"],
    },
    {
        "name": "Attention to Detail (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/attention-to-detail-new/",
        "description": "Measures ability to identify errors, inconsistencies, and discrepancies in data or documents accurately.",
        "test_type": "K",
        "job_levels": ["Entry-Level", "General Population", "Graduate"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 15,
        "languages": ["English (USA)"],
        "keywords": ["attention to detail", "accuracy", "proofreading", "clerical", "quality control", "administrative"],
    },
    {
        "name": "Supply Chain Management (New)",
        "url": "https://www.shl.com/solutions/products/product-catalog/view/supply-chain-management-new/",
        "description": "Multi-choice test measuring knowledge of supply chain principles, logistics, procurement, and operations management.",
        "test_type": "K",
        "job_levels": ["Mid-Professional", "Professional Individual Contributor"],
        "remote_testing": True,
        "adaptive": False,
        "duration_minutes": 20,
        "languages": ["English (USA)"],
        "keywords": ["supply chain", "logistics", "procurement", "operations", "inventory", "manufacturing"],
    },
]

# Build a lookup dict by name for quick access
CATALOG_BY_NAME = {item["name"].lower(): item for item in CATALOG}

def get_catalog_summary():
    """Returns a compact text summary of the catalog for LLM context."""
    lines = []
    for item in CATALOG:
        levels = ", ".join(item["job_levels"])
        langs = ", ".join(item["languages"][:3]) + (f" +{len(item['languages'])-3} more" if len(item["languages"]) > 3 else "")
        lines.append(
            f"- {item['name']} | Type: {item['test_type']} | Levels: {levels} | "
            f"Remote: {'Yes' if item['remote_testing'] else 'No'} | "
            f"Adaptive: {'Yes' if item['adaptive'] else 'No'} | "
            f"~{item['duration_minutes']} min | Lang: {langs}\n"
            f"  Desc: {item['description']}"
        )
    return "\n".join(lines)
